apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: master2
  name: master2
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: master2
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: master2
    spec:
      containers:
      - env:
        - name: MARIADB_EXTRA_FLAGS
          value: --max-connect-errors=5000 --max_connections=300 --innodb_buffer_pool_size=2G
            --max_allowed_packet=512M
        - name: MARIADB_GALERA_CLUSTER_ADDRESS
          value: gcomm://master1
        - name: MARIADB_GALERA_CLUSTER_NAME
          value: cluster_galera
        - name: MARIADB_GALERA_MARIABACKUP_PASSWORD
          value: mariabackup
        - name: TZ
          value: America/Santiago
        image: miguelwill/mariadb-galera-udf:latest
        imagePullPolicy: ""
        name: master2
        ports:
        - containerPort: 3306
        - containerPort: 4444
        - containerPort: 4567
        - containerPort: 4568
        resources: {}
        volumeMounts:
        - mountPath: /bitnami/mariadb
          name: db-data2
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: db-data2
        persistentVolumeClaim:
          claimName: db-data2
status: {}
