apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: master1
  name: master1
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: master1
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: master1
    spec:
      containers:
      - env:
        - name: MARIADB_DATABASE
          value: dbsite
        - name: MARIADB_EXTRA_FLAGS
          value: --max-connect-errors=5000 --max_connections=300 --innodb_buffer_pool_size=512M
            --max_allowed_packet=512M --max_binlog_size=200M
        - name: MARIADB_GALERA_CLUSTER_BOOTSTRAP
          value: "yes"
        - name: MARIADB_GALERA_CLUSTER_NAME
          value: "cluster_galera"
        - name: MARIADB_GALERA_MARIABACKUP_PASSWORD
          value: mariabackup
        - name: MARIADB_PASSWORD
          value: dbpass
        - name: MARIADB_ROOT_PASSWORD
          value: root
        - name: MARIADB_USER
          value: dnuser
        - name: TZ
          value: America/Santiago
        image: miguelwill/mariadb-galera-udf:latest
        imagePullPolicy: ""
        name: master
        ports:
        - containerPort: 3306
        - containerPort: 4444
        - containerPort: 4567
        - containerPort: 4568
        resources: {}
        volumeMounts:
        - mountPath: /bitnami/mariadb
          name: db-data1
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: db-data1
        persistentVolumeClaim:
          claimName: db-data1
status: {}
