apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: master2
  name: master2
spec:
  ports:
  - name: "3306"
    port: 3306
    targetPort: 3306
  - name: "4444"
    port: 4444
    targetPort: 4444
  - name: "4567"
    port: 4567
    targetPort: 4567
  - name: "4568"
    port: 4568
    targetPort: 4568
  selector:
    io.kompose.service: master2
status:
  loadBalancer: {}
